easy_admin:
  #  disabled_actions: ['edit']
    site_name: '<img src="/img/logoNAO.png" /> NAO Admin'
    formats:
        date:     'd/M/Y'
        datetime: 'd/M/Y'    
    design:
        brand_color: '#a671ab'
        color_scheme: 'light'
        menu:
            - { entity: 'Aves', icon: 'qq' }
            - { entity: 'Newsletter', icon: 'envelope' }
            - { entity: 'Observation', icon: 'camera-retro' }
            - { entity: 'Post', icon: 'pencil' }
            - { entity: 'User', icon: 'user' }
    entities:
      Aves: 
        class: App\Entity\Aves
        list:
          title: "Base de données Aves"
          sort: ['commonName', 'ASC']
          fields: 
            - { property: 'commonName',     label: 'Nom Commun' }
            - { property: 'scientificName', label: 'Nom Scientifique' }
            - { property: 'author',         label: 'Auteur' }
            - { property: 'order',          label: 'Ordre' }
            - { property: 'family',         label: 'Famille' }
            - { property: 'habitat',        label: 'Habitat' }
        form:
          fields:
            - { property: 'commonName',     label: 'Nom Commun' }
            - { property: 'scientificName', label: 'Nom Scientifique' }
            - { property: 'author',         label: 'Auteur' }
            - { property: 'order',          label: 'Ordre' }
            - { property: 'family',         label: 'Famille' }
            - { property: 'habitat',        label: 'Habitat' }
      Newsletter: 
        class: App\Entity\Newsletter
        list:
          title: "Liste d'emails inscrit à la Newsletter"
          fields: 
            - { property: 'Email', label: 'Email', type: 'email' }
      Observation: 
        class: App\Entity\Observation
        list:
          title: "Liste des Observations"
          fields: 
            - { property: 'commonName',  label: 'Nom Commun' }
            - { property: 'image',       label: 'Image',       type: 'image', base_path: '/img/observations/' }
            - { property: 'date',        label: 'Date',        type: datetime}
            - { property: 'numbers',     label: 'Nombre' }
            - { property: 'department',  label: 'Departement', type: 'integer' }
            - { property: 'latitude',    label: 'Latitude' }
            - { property: 'longitude',   label: 'Longitude' }
        form:
          fields:
            - { property: 'commonName',  label: 'Nom Commun' }
            - { property: 'numbers',     label: 'Nombre' }
            - { property: 'image',       label: 'Image'}
            - { property: 'department',  label: 'Departement'}
            - { property: 'latitude',    label: 'Latitude' }
            - { property: 'longitude',   label: 'Longitude' }
            - { property: 'date',        label: 'Date'}
      Post: 
        class: App\Entity\Post
        label: Article
        list:
          title: "Liste des Articles"
          fields: 
            - { property: 'image',     label: 'Image',  type: 'image', base_path: '/img/blog/' }
            - { property: 'title',     label: 'Titre' }
            - { property: 'date',      label: 'Date',   type: 'datetime' }
            - { property: 'author',    label: 'Auteur' }
            - { property: 'published', label: 'Publié', type: 'toggle' }
        form:
          fields:
            - { property: 'title',     label: 'Titre' }
            - { property: 'article',   label: 'Article' }
            - { property: 'author',    label: 'Auteur' }
            - { property: 'date',      label: 'Date'}
            - { property: 'image',     label: 'Image' }
            - { property: 'published', label: 'Publié' }
      User: 
        class: App\Entity\User
        help: 'Liste des roles disponible: ROLE_ADMIN - ROLE_NATURALIST - ROLE_USER'
        label: Utilisateur
        list:
          title: "Liste des Utilisateurs"
          sort: ['firstName', 'ASC']
          fields: 
            - { property: 'firstName', label: 'Prénom' }
            - { property: 'lastname',  label: 'Nom' }
            - { property: 'userName',  label: 'Identifiant',  type: 'email' }
            - { property: 'roles',     label: 'Role',         type: 'array'}
            - { property: 'isActive',  label: 'Actif',        type: 'toggle' }
        form:
          fields: 
              - { property: 'userName',  label: 'Identifiant', type: 'email' }
              - { property: 'firstName', label: 'Prénom' }
              - { property: 'lastname',  label: 'Nom',         type: 'text' }
              - { property: 'roles',     label: 'Role'}
              - { property: 'isActive',  label: 'Actif' }