easy_admin:
   site_name: 'NAO Admin'
   entities:
       # List the entity class name you want to manage
       - App\Entity\Aves
       - App\Entity\Newsletter
       - App\Entity\Observation
       - App\Entity\Post
       - App\Entity\User
