vich_uploader:
    db_driver: orm

    mappings:
       observations_image:
           uri_prefix: /images/observations
           upload_destination: '%kernel.project_dir%/public/images/observations'
        ### VOIR MENTOR ###
        #    namer: Vich\UploaderBundle\Naming\UniqidNamer
