homepage:
    path: /
    controller: App\Controller\NAO\HomePageController::index

about:
    path: /apropos
    controller: App\Controller\NAO\AboutController::index

join_us:
    path: /adherer
    controller: App\Controller\NAO\JoinUsController::index

join_us_show_file:
    path: /formulaire-adhesion
    controller: App\Controller\NAO\JoinUsController::showFiles

observe:
    path: /observer
    controller: App\Controller\NAO\ObserveController::index

list_observations:
    path: /list-des-observations
    controller: App\Controller\NAO\ListObservationsController::index

map:
    path: /carte
    controller: App\Controller\NAO\MapController::index

map_show_list:
    path: /carte-liste/{commonName}
    controller: App\Controller\NAO\MapController::showList

blog:
    path: /blog
    controller: App\Controller\NAO\BlogController::index

faq:
    path: /faq
    controller: App\Controller\NAO\FaqController::index

contact:
    path: /contact
    controller: App\Controller\NAO\ContactController::index

my_observations:
    path: /mes-observations
    controller: App\Controller\NAO\MyObservationsController::index

naturalist_validations:
    path: /naturalist/validations
    controller: App\Controller\Naturalist\ValidationsController::index

naturalist_obs_valid:
    path: /naturalist/observation/valider/{id}
    controller: App\Controller\Naturalist\ValidationsController::valid
    requirements:
        page: '\d+'

naturalist_obs_remove:
    path: /naturalist/observation/supprimer/{id}
    controller: App\Controller\Naturalist\ValidationsController::remove
    requirements:
        page: '\d+'

naturalist_obs_modify:
    path: /naturalist/observation/modifier/{id}
    controller: App\Controller\Naturalist\ValidationsController::modify
    requirements:
        page: '\d+'

naturalist_articles:
    path: /naturalist/articles
    controller: App\Controller\Naturalist\ArticlesController::index

naturalist_articles_new:
    path: /naturalist/articles/nouvel-article
    controller: App\Controller\Naturalist\ArticlesController::new

naturalist_articles_remove:
    path: /naturalist/articles/supprimer/{id}
    controller: App\Controller\Naturalist\ArticlesController::remove
    requirements:
        page: '\d+'

naturalist_articles_modify:
    path: /naturalist/articles/modifier/{id}
    controller: App\Controller\Naturalist\ArticlesController::modify
    requirements:
        page: '\d+'

security_login:
    path: /connexion
    controller: App\Controller\Security\LoginController::index

security_signup:
    path: /inscription
    controller: App\Controller\Security\SignupController::index

security_logout:
    path: /deconnexion
    controller: App\Controller\Security\LoginController::logout

newsletter:
    path: /newsletter
    controller: App\Controller\NAO\NewsletterController::index

plan-du-site:
    path: /plan-du-site
    controller: App\Controller\NAO\PlanSiteController::index