App\Entity\Aves:
    type: entity
    table: nao_aves
    repositoryClass: App\Repository\AvesRepository
    manyToMany:
        observations:
            targetEntity: App\Entity\Observation
            mappedBy: aveses
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        order:
            name: order
            type: string
            length: 25
        family:
            name: family
            type: string
            length: 25
        scientificName:
            name: scientific_name
            type: string
            length: 60
        author:
            name: author
            type: string
            length: 60
        commonName:
            name: common_name
            type: string
            lenght: 120
        habitat:
            name: habitat
            type: integer
            lenght: 1
