App\Entity\Observation:
    type: entity
    table: nao_observation
    repositoryClass: App\Repository\ObservationRepository
    manyToMany:
        aveses:
            targetEntity: App\Entity\Aves
            inversedBy: observations
            fetch: EAGER
    manyToOne:
        user:
            targetEntity: App\Entity\User
            joinColumn:
                nullable: false
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        commonName:
            name: common_name
            type: string
        date:
            name: date
            type: date
        latitude:
            name: latitude
            type: string
        longitude:
            name: longitude
            type: string
        department:
            name: department
            type: integer
        numbers:
            name: numbers
            type: integer
        image:
            name: image
            type: string
        content:
            name: content
            type: string
            nullable: true
        isValid:
            name: is_valid
            type: boolean
