App\Entity\Post:
    type: entity
    table: nao_post
    repositoryClass: App\Repository\PostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        image:
            name: image
            type: string
        title:
            name: title
            type: string
        article:
            name: article
            type: text
        author:
            name: author
        date:
            name: date
            type: date
        published:
            name: published
            type: boolean
        