App\Entity\User:
    type: entity
    table: nao_user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            name: username
            type: string
            length: 25
            unique: true
        firstName:
            name: first_name
            type: string
            length: 25
        lastName:
            name: last_name
            type: string
            length: 25
        password:
            name: password
            type: string
            lenght: 64
        roles:
            name: roles
            type: simple_array
        isActive:
            name: is_active
            type: boolean
